### ISSUE TITLE
Help running this

### ISSUE THREAD

**Issue by Tranberry** [Dwood15/LuaNEAT-rnn#1]
> Take these scripts and place them in: \lua\snes\ **_Select a starting point_** and create a save state - name it DP1.state -

What does select a starting point mean?

---

`LuaInterface.LuaScriptException: [string "main"]:1357: attempt to perform arithmetic on global 'CURRENTRUN' (a nil value)`

It seems like it won't create any folders except the AIData one. I'm not sure I'm reading this correctly.

---

I got it running by making a clean install of BIZHawk, but now it culls all species.

```
New generation
Removing stale, there are: 30 species
genome count for specie #1: 1
Staleness: 0 for species: 1
species.staleness: 0.001
genome count for specie #2: 1
Staleness: 0 for species: 2
species.staleness: 0.001
genome count for specie #3: 1
Staleness: 0 for species: 3
species.staleness: 0.001
genome count for specie #4: 1
Staleness: 0 for species: 4
species.staleness: 0.001
genome count for specie #5: 1
Staleness: 0 for species: 5
species.staleness: 0.001
genome count for specie #6: 1
Staleness: 0 for species: 6
species.staleness: 0.001
genome count for specie #7: 1
Staleness: 0 for species: 7
species.staleness: 0.001
genome count for specie #8: 1
Staleness: 0 for species: 8
species.staleness: 0.001
genome count for specie #9: 1
Staleness: 0 for species: 9
species.staleness: 0.001
genome count for specie #10: 1
Staleness: 0 for species: 10
species.staleness: 0.001
genome count for specie #11: 1
Staleness: 0 for species: 11
species.staleness: 0.001
genome count for specie #12: 1
Staleness: 0 for species: 12
species.staleness: 0.001
genome count for specie #13: 1
Staleness: 0 for species: 13
species.staleness: 0.001
genome count for specie #14: 1
Staleness: 0 for species: 14
species.staleness: 0.001
genome count for specie #15: 1
Staleness: 0 for species: 15
species.staleness: 0.001
genome count for specie #16: 1
Staleness: 0 for species: 16
species.staleness: 0.001
genome count for specie #17: 1
Staleness: 0 for species: 17
species.staleness: 0.001
genome count for specie #18: 1
Staleness: 0 for species: 18
species.staleness: 0.001
genome count for specie #19: 1
Staleness: 0 for species: 19
species.staleness: 0.001
genome count for specie #20: 1
Staleness: 0 for species: 20
species.staleness: 0.001
genome count for specie #21: 1
Staleness: 0 for species: 21
species.staleness: 0.001
genome count for specie #22: 1
Staleness: 0 for species: 22
species.staleness: 0.001
genome count for specie #23: 1
Staleness: 0 for species: 23
species.staleness: 0.001
genome count for specie #24: 1
Staleness: 0 for species: 24
species.staleness: 0.001
genome count for specie #25: 1
Staleness: 0 for species: 25
species.staleness: 0.001
genome count for specie #26: 1
Staleness: 0 for species: 26
species.staleness: 0.001
genome count for specie #27: 1
Staleness: 0 for species: 27
species.staleness: 0.001
genome count for specie #28: 1
Staleness: 0 for species: 28
species.staleness: 0.001
genome count for specie #29: 1
Staleness: 0 for species: 29
species.staleness: 0.001
genome count for specie #30: 1
Staleness: 0 for species: 30
species.staleness: 0.001
 30 spec survived the stale calculations.

Removing weak species, there are: 30 but 0 survived
We killed all species, created new pool
LuaInterface.LuaScriptException: [string "main"]:960: bad argument #2 to 'random' (interval is empty)
```

the console also writes this:
`Cannot move multiple files to a single file.`

**Comment by Tranberry** [comment]
> What does select a starting point mean?

Duh, it means start a level or get to the point you want the AI to start.

---

I haven't managed to not have it kill of all species every time so I'm stuck running _generation zero_ each time 😢

**Comment by Dwood15** [comment]
Good to hear you got it working-ish. Yes, the extinction is a known bug. I began school again and got distracted by other projects a while ago, so I haven't debugged the issues with extinction events. 

Find where it's killing off species, then try and search why it's killing them off. It's been about 6+ months since i've looked at this script, but seeing that there's at least some interest with my modification, I may revisit it sooner than later.

**Comment by Thiria88** [comment]
I was also having problems with no species surviving. I changed:
		local result = math.floor(species.averageFitness / (totalAvgFitness * MINPOPULATION))
to:
		local result = math.floor((species.averageFitness / totalAvgFitness) * MINPOPULATION)
on row 896 in neatevolve.lua. I do not know if this is the correct solution, but it seems to be (kinda?) working.

**Comment by Dwood15** [comment]
You might have actually fixed the issue with the code! I'll check it out this weekend

**Comment by Dwood15** [comment]
So, @Thiria88 and @Tranberry! I added the change which should reduce the chance of it killing off each species every time. I haven't debugged the change yet (lol) but I think it should help for now.

**Comment by Tranberry** [comment]
Hurray, I'll give it a go in a day or so!

**Comment by Dwood15** [comment]
Closing this, as I believe it is complete
